WebDeck/Pages/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Primitives;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Controller;
using OBS.WebSocket.NET;
using SpotifyAPI.Web;
using WebDeck.Models;
using WebDeck.Services;

namespace WebDeck.Pages
{
    [Authorize]
    public class AdminModel : PageModel
    {
        public ConfigModel config;
        public ObsWebSocket obsWebSocket;
        public readonly SpotifyService spotifyService;
        private readonly IWebHostEnvironment env;

        public AdminModel(ConfigModel config, ObsWebSocket obsWebSocket, SpotifyService spotifyService, IWebHostEnvironment env)
        {
            this.config = config;
            this.obsWebSocket = obsWebSocket;
            this.spotifyService = spotifyService;
            this.env = env;
        }



        public void OnGet()
        {
            string br = "";
        }

        public async Task<IActionResult> OnPostSpotify()
        {
            string requesturl = null;
            string thisurl = null;
            if (this.env.IsDevelopment())
            {
                thisurl = "http://localhost:5000/Admin?handler=SpotifyReturn";
            }
            else
            {
                thisurl = "http://bullshit.here:2000/Admin?handler=SpotifyReturn";
            }
            requesturl = await spotifyService.GetLoginRequest(thisurl);
            return Redirect(requesturl);
        }

        public async Task<IActionResult> OnGetSpotifyReturn(string code)
        {
            string requesturl = null;
            if (this.env.IsDevelopment())
            {
                requesturl = "http://localhost:5000/Admin?handler=SpotifyReturn";
            }
            else
            {
                requesturl = "http://bullshit.here:2000/Admin?handler=SpotifyReturn";
            }
            await spotifyService.HandleLoginRespone(code, requesturl);
            return Redirect("/Admin");
        }
        public async Task<IActionResult> OnGetSpotifyReturnDeck(string code)
        {
            string requesturl = null;
            if (this.env.IsDevelopment())
            {
                requesturl = "http://localhost:5000/Admin?handler=SpotifyReturnDeck";
            }
            else
            {
                requesturl = "http://bullshit.here:2000/Admin?handler=SpotifyReturnDeck";

            }
            await spotifyService.HandleLoginRespone(code, requesturl);
            return Redirect("/Deck");

        }

        public async Task<IActionResult> OnGetWay2Async(string data)
        {

            return StatusCode(200);
        }

        public void OnPost()
        {
            if (obsWebSocket.IsConnected)
            {
                obsWebSocket.Disconnect();
            }
            else
            {
                try
                {
                    obsWebSocket.Connect(config.oBSConfig.Connectionstring, config.oBSConfig.Password);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"OBS could not connect: {ex.InnerException}");
                }
            }
        }
    }
}

WebDeck/Pages/Deck.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Server.IIS.Core;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using OBS.WebSocket.NET;
using OBS.WebSocket.NET.Types;
using WebDeck.Models;
using WebDeck.Models.SQL;
using System.IO.Pipes;
using System.Net.Http;
using WebDeck.Services;

namespace WebDeck.Pages
{
    public class DeckModel : PageModel
    {
        private ObsWebSocket ObsWebSocket;
        private readonly HueService hueService;
        private List<OBSScene> SceneList;
        private readonly ILogger<DeckModel> _logger;
        private readonly DumbAssIconListForLazyDevs dumbAssIcon;
        public List<IconConfig> iconPage;
        private Random rnd = new Random();
        private readonly IconConfigContext _iconConfigContext;
        private readonly ConfigModel config;
        private readonly OBSService oBSService;
        private readonly SpotifyService spotifyService;
        private readonly BlacklightService blacklightService;

        public DeckModel(ObsWebSocket obsWebSocket, HueService hueService, ILogger<DeckModel> logger, DumbAssIconListForLazyDevs dumbAssIcon, IconConfigContext iconConfigContext, ConfigModel config, 
                OBSService oBSService, SpotifyService spotifyService, BlacklightService blacklightService)
        {
            this.ObsWebSocket = obsWebSocket;
            this.hueService = hueService;
            this._logger = logger;
            this._iconConfigContext = iconConfigContext;
            this.config = config;
            this.oBSService = oBSService;
            this.spotifyService = spotifyService;
            this.blacklightService = blacklightService;
            this.dumbAssIcon = dumbAssIcon;
            this.iconPage = new List<IconConfig>();
        }
        public async Task OnGet()
        {
            await DoStuff();
        }

        private async Task DoStuff()
        {
            using (this._iconConfigContext)
            {
                this.iconPage = _iconConfigContext.IconConfig.ToList();
            }
            //TODO: move "checkDisabled" into an own methode for each serivce 
            if (spotifyService.client == null)
            {
                iconPage.Where(x => x.CommandType == "SPOTIFY").ToList().ForEach(x => x.Disabled = true);
            }
            if ((await oBSService.IsConnected()) == false)
            {
                iconPage.Where(x => x.CommandType == "OBS").ToList().ForEach(x => x.Disabled = true);
            }
        }

    }
}

WebDeck/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebDeck.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebDeck/Pages/IconConfiguration.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
//using Unosquare.Swan;
using WebDeck.Models;
using WebDeck.Models.SQL;

namespace WebDeck.Pages
{
    [Authorize]

    public class IconConfigurationModel : PageModel
    {
        private readonly IServiceScopeFactory serviceScopeFactory;
        private readonly ConfigModel configModel;
        public List<IconConfig> iconConfigs;
        public List<string> UsedProperties;
        public string teststring = "hugo";
        [BindProperty]  public string hugo2 { get; set; }

        public IconConfigurationModel(IServiceScopeFactory serviceScopeFactory, ConfigModel configModel  )
        {
            this.serviceScopeFactory = serviceScopeFactory;
            this.configModel = configModel;
            this.UsedProperties = new List<string>() { "IconPath", "CommandType", "CommandText", "PosX", "PosY", "FkPage" };
        }
        public async Task OnGet()
        {
            await GetIconConfig();
        }
        
        //TODO: test 
        private async Task GetIconConfig()
        {
            using (var scope = serviceScopeFactory.CreateScope())
            {

                try
                {
                    using (var _dbcontext = scope.ServiceProvider.GetRequiredService<IconConfigContext>())
                    {
                        iconConfigs = _dbcontext.IconConfig.Where(x => x.FkPage == 1).ToList();
                    }
                }
                catch (Exception ex)
                {
                    string br = "";
                    throw;
                }
            }
        }

        private async Task OnPostAsnyc()
        {
            var newstring = teststring;
            await GetIconConfig();
        }

        private void OnPost()
        {
          //  GetIconConfig().Await();
        }

        //private async Task OnPostHugoAsync()
        //{
        //    bool saveit = true;
        //    await GetIconConfig();
        //    string br = "";

        //}

        //public void OnPostPeter(IconConfigurationModel newiconConfigs)
        //{
        //    var temp = iconConfigs.Count;
        //    GetIconConfig().Await();
        //}
        public void OnPostPeter()
        {
            var temp = iconConfigs.Count;
           // GetIconConfig().Await();
        }

        public void OnPostHugo()
        {
             var temp = iconConfigs.Count;
          //GetIconConfig().Await();
        }
    }
}

WebDeck/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebDeck.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

WebDeck/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebDeck.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebDeck/Pages/Test.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebDeck.Pages
{
    public class TestModel : PageModel
    {
        public string Message { get; set; }
        public void OnGet()
        {
            Message = "Get used";
        }
        public void OnPostHugo()
        {
            Message = "Post used";
        }
    }
}

WebDeck/Pages/Admin.cshtml
@page
@model AdminModel
@{
    ViewData["Title"] = "Admin";
}

<h1>Admin</h1>
<div>

    <div class="input-group mb-3">

        @if (Model.obsWebSocket.IsConnected)
        {
            <form method="post"><button class="btn btn-danger">Disconnect OBS</button></form>

        }
        else
        {
            <form method="post"><button class="btn btn-success">Connect OBS</button></form>
        }
    </div>

    <div class="input-group mb-3">

        @if (Model.spotifyService.client != null)
        {
            <form method="post" asp-page-handler="Spotify"><button class="btn btn-danger">Disconnect from Spotify</button></form>
        }
        else
        {
            <form method="post" asp-page-handler="Spotify"><button class="btn btn-success">Login to Spotify</button></form>
        }


    </div>

    <div>


    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">OBSConnectionstring</span>
        </div>
        <input type="text" class="form-control" placeholder="@Model.config.oBSConfig.Connectionstring" aria-label="Username" aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">OBSPassword</span>
        </div>
        <input type="text" class="form-control" placeholder="@Model.config.oBSConfig.Password" aria-label="Username" aria-describedby="basic-addon1">
    </div>
</div>

<script language="JavaScript" type="text/javascript" src="/vendor.min.js"></script>
<script>

    $("[name='toggleChk']").bootstrapSwitch();

    $('input[name ="toggleChk"]').on('switchChange.bootstrapSwitch', function (event, state) {
        console.log(this); // DOM element
        console.log(event); // jQuery event
        console.log(state); // true | false
    });
</script>

WebDeck/Pages/Deck.cshtml
@page
@model WebDeck.Pages.DeckModel
@{
    ViewData["Title"] = "Deck";

}

<div class="container-fluid h-100" style="position: fixed;">
    @for (int y = 0; y <= 3; y++)
    {
        <div class="row   d-flex justify-content-center flex-grow-1" style="height:15vh" align="center">
            @for (int x = 0; x <= 7; x++)
            {
                <div class="col   d-flex flex-grow-1 justify-content-center" align="center">
                    @{ var icon = Model.iconPage.FirstOrDefault(e => e.PosX == x && e.PosY == y); }
                    @if (icon != null)
                    {
                        var color = (icon.Disabled) ? "gray" : "black";

                        <button class="btn " name="val" value="@icon.CommandType#@icon.CommandText" onclick='sendDeckCommand(this)'>
                            <i class="DeckButton @icon.IconPath fa-4x" style="color: @color;"></i><br />@icon.DisplayName
                        </button>

                    }
                    else
                    {
                        <button class="btn">
                            <i class="far fa-square" style="color: lightgray;"></i><br />Empty
                        </button>
                    }
                </div>
            }
        </div>
    }
</div>

<script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
<script src="~/js/DeckHub.js"></script>

WebDeck/Pages/IconConfiguration.cshtml
@page
@model WebDeck.Pages.IconConfigurationModel
@{
    ViewData["Title"] = "IconConfig";
}

<div class="container">
    <div class="row">
        @foreach (var propname in Model.UsedProperties)
        {
            <div class="col d-flex flex-grow-1 justify-content-center">
                <p>@propname</p>
            </div>
        }
    </div>
    @foreach (var fuu in Model.iconConfigs)
    {
        <div class="row">
            @foreach (var propname in Model.UsedProperties)
            {
                <div class="col d-flex flex-grow-1 justify-content-center">
                    <input class="form-control " id="exampleFormControlTextarea1" value="@fuu.GetType().GetProperty(propname).GetValue(fuu,null)">
                </div>
            }
        </div>
    }
 
    <div>
        <form method="post" asp-page-handler="Peter" asp-for="teststring">
            <label asp-for="teststring"></label>
            <input  type="text" asp-for="teststring"/>
            <button type="submit" ></button>
            @*<button type="submit" class="btn btn-warning">MakePersistent</button>*@
        </form>
    </div>
</div>

WebDeck/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1><i class="fas fa-angry"></i>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebDeck/Pages/Test.cshtml
@page
@model WebDeck.Pages.TestModel
@{
    ViewData["Title"] = "IconConfig";
}

<h3>@Model.Message</h3>
<form method="post"  asp-page-handler="Hugo"><button class="btn btn-default">Click to post</button></form>
<p><a href="/handlerexample" class="btn btn-default">Click to Get</a></p>